#Program outputs wether today is a weekday or not
#Reference: https://pythontic.com/datetime/date/weekday
#Author: Joana Ruas

import datetime #importing Python datetime module

weekDays=('Moday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday') #Setting up tuple for weekdays

#TodayDateInput=tuple(input('Please insert todays date (yyyy,mm,dd): '))

TodayDate=datetime.date(2021,2,20)
TodayWeekday=TodayDate.weekday() #weekday fucntion assigns an integer to a Weekday, where 0 is Monday
#the tupple is aligned with the weekdays function relation. So [0] in the tuple is also monday.
# the next lines converts the inter to a String, using the tupple and the position in the tuple generated by the weekday function.
if TodayWeekday<5:
    TodayString=weekDays[TodayWeekday] 
    print('Unfortunalty today is {}, weekday' . format(TodayString))
else:
    print('Today is weekend!')



